### PR TITLE
T/139a: getOptimalPosition() utility does not work when the parent element has a scroll

### LINKED ISSUE #139: getOptimalPosition utility does not work when parent element has scroll
See: https://github.com/ckeditor/ckeditor5-ui/issues/171#issuecomment-287310263

### PR DESCRIPTION
**Pull request by oleq**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Fix: getOptimalPosition() utility does not work when the parent element has a scroll. Closes #139.

### CODE REVIEW

File: src/dom/position.js [hunk 1]
```diff
@@ -99,14 +99,31 @@ export function getOptimalPosition( { element, target, positions, limiter, fitIn
...
+
+		// (https://github.com/ckeditor/ckeditor5-utils/tree/t/139)
+		// If there's some positioned ancestor of the panel, not only its position must be taken into
+		// consideration (see above) but also its internal scrolls. Scroll have an impact here because `Rect`
+		// is relative to the viewport (it doesn't care about scrolling), while `position: absolute`
+		// must compensate that scrolling.
+		left += positionedElementAncestor.scrollLeft;
+		top += positionedElementAncestor.scrollTop;
+
+		// (https://github.com/ckeditor/ckeditor5-utils/tree/t/139)
```
Comment (oskarwrobel) [inline src/dom/position.js]: This is a link to the branch not to the issue.

File: src/dom/position.js [hunk 2]
```diff
@@ -99,14 +99,31 @@ export function getOptimalPosition( { element, target, positions, limiter, fitIn
...
 		const ancestorPosition = getAbsoluteRectCoordinates( new Rect( positionedElementAncestor ) );
+		const ancestorComputedStyles = global.window.getComputedStyle( positionedElementAncestor );
 
+		// (#126) If there's some positioned ancestor of the panel, then its `Rect` must be taken into
+		// consideration. `Rect` is always relative to the viewport while `position: absolute` works
+		// with respect to that positioned ancestor.
 		left -= ancestorPosition.left;
 		top -= ancestorPosition.top;
+
+		// (https://github.com/ckeditor/ckeditor5-utils/tree/t/139)
```
Comment (oskarwrobel) [inline src/dom/position.js]: This is a link to the branch not to the issue.

**Comment by oskarwrobel** [comment]
Missing 100% CC in utils.

**Comment by oskarwrobel** [comment]
Besides CC everything works and looks like it should!

File: src/dom/position.js [hunk 3]
```diff
@@ -99,14 +99,31 @@ export function getOptimalPosition( { element, target, positions, limiter, fitIn
...
 	let { left, top } = getAbsoluteRectCoordinates( bestPosition );
 
-	// (#126) If there's some positioned ancestor of the panel, then its rect must be taken into
-	// consideration. `Rect` is always relative to the viewport while `position: absolute` works
-	// with respect to that positioned ancestor.
 	if ( positionedElementAncestor ) {
 		const ancestorPosition = getAbsoluteRectCoordinates( new Rect( positionedElementAncestor ) );
+		const ancestorComputedStyles = global.window.getComputedStyle( positionedElementAncestor );
 
+		// (#126) If there's some positioned ancestor of the panel, then its `Rect` must be taken into
```
Comment (oskarwrobel) [inline src/dom/position.js]: This should be full link to the ticket because this is a ticket from different repo https://github.com/ckeditor/ckeditor5-ui-default/issues/126

**Comment by oleq** [comment]
@oskarwrobel Found it https://github.com/ckeditor/ckeditor5-utils/pull/141/commits/dd9f46eaabdbec5c9fb19a4749b79b8a0526a260 ;-)
