### PR TITLE
t/108a: 	Implemented global module to create stubbable access to global DOM objects

### LINKED ISSUE #108: Failing getOptimalPosition tests on master
https://travis-ci.org/ckeditor/ckeditor5/builds/181701427

A follow-up of https://github.com/ckeditor/ckeditor5-ui-default/issues/137.

### PR DESCRIPTION
**Pull request by oleq**
Closes #108.

### CODE REVIEW

File: src/dom/global.js [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+ * testing, i.e. stubbing native properties
+ *
+ *		import global from 'ckeditor5/utils/dom/global.js';
+ *
+ *		const window = global.window;
+ *
+ * 		// This stub will work for any code using global module in tests.
+ *		testUtils.sinon.stub( window, 'innerWidth', 10000 );
+ */
+export default { document, window };
```
Comment (oleq) [inline src/dom/global.js]: I wonder if that could be done better. ATM it's

```js
import global from './global.js';
const window = global.window;
testUtils.sinon.stub( window, 'innerWidth', 10000 );
```

Maybe some way to have `import { window } from './global.js';`?

File: tests/dom/global.js [hunk 2]
```diff
@@ -0,0 +1,24 @@
+/**
+ * @license Copyright (c) 2003-2016, CKSource - Frederico Knabben. All rights reserved.
+ * For licensing, see LICENSE.md.
+ */
+
+/* global window, document */
+
+import { window as globWindow, document as globDocument } from 'ckeditor5/utils/dom/global.js';
```
Comment (oleq) [inline tests/dom/global.js]: I hope bundlers will handle it properly. Otherwise, it's a simple matter of `const nativeDomWindow = window` before importing and then `expect( window ).to.equal( nativeDomWindow );`

File: src/dom/global.js [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+ */
+
+/**
+ * A helper (module) giving an access to the global `document` DOM object.
+ * Accessing this object using this helper allows easy and bulletproof
+ * testing, i.e. stubbing native properties:
+ *
+ *		import { document } from 'ckeditor5/utils/dom/global.js';
+ *
+ * 		// This stub will work for any code using global module in tests.
```
Comment (Reinmar) [inline src/dom/global.js]: Indentation.

File: src/dom/global.js [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+export { document };
+
+/**
+ * A helper (module) giving an access to the global `window` DOM object.
+ * Accessing this object using this helper allows easy and bulletproof
+ * testing, i.e. stubbing native properties:
+ *
+ *		import { window } from 'ckeditor5/utils/dom/global.js';
+ *
+ * 		// This stub will work for any code using global module in tests.
```
Comment (Reinmar) [inline src/dom/global.js]: Indentation.

File: tests/dom/global.js (hunk 2 above)
Comment (Reinmar) [inline tests/dom/global.js]: I don't think that it may cause any problems.

File: src/dom/global.js [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+ * A helper (module) giving an access to the global `document` DOM object.
+ * Accessing this object using this helper allows easy and bulletproof
+ * testing, i.e. stubbing native properties:
+ *
+ *		import { document } from 'ckeditor5/utils/dom/global.js';
+ *
+ * 		// This stub will work for any code using global module in tests.
+ *		testUtils.sinon.stub( document, 'dir', 'rtl' );
+ */
+export { document };
```
Comment (Reinmar) [inline src/dom/global.js]: WAIT... what are you actually doing here? Exporting document as document... That doesn't make sense and I don't think it may actually work. Since you're exporting exactly the same object, then stubbing properties on it won't work (in case of window props).

File: tests/dom/global.js (hunk 2 above)
Comment (Reinmar) [inline tests/dom/global.js]: I take back my previous comment. I didn't read this PR carefully before writing it. Now I have no idea why all this works at all.

**Comment by oleq** [comment]
>  there's some quirk which make them work.

Probably, yes. I might have bulletproofed tests even more by replacing `window.scrollX =...` with `stinon.stub( window, 'scrollX', ... )` and that's why it works.

I guess my changeset changed nothing but this thing :D
