### PR TITLE
Changed: Make EmitterMixin#_listeningTo and _emitterId private

### LINKED ISSUE #114: EmitterMixin#_listeningTo should not be stringified.
Anything that mixes `EmitterMixin` and listens to something, gets `_listeningTo` property. This is also true, of course, for `LiveRange`. Such `LiveRange`, when stringified to JSON, has that property. This is incorrect for `LiveRange` and will probably be incorrect for anything that uses `EmitterMixin`.

This needs to be fixed, and here are two approaches:

1. Specify `toJSON` for each class mixing `EmitterMixin`. In that custom `toJSON` remove `_listeningTo`. This is bad because we need to remember about it each time.
2. Make `_listeningTo` not enumerable. I think this is a better approach, especially since this is hidden, private property.

### PR DESCRIPTION
**Pull request by scofalik**
Fixes #114.

### CODE REVIEW

**Comment by scofalik** [comment]
It would be nice to followup this with an issue in which we would (try to) get rid off `ck-expando` thing.

**Comment by Reinmar** [comment]
Not sure where, but CC is missing: https://travis-ci.org/ckeditor/ckeditor5-utils/builds/190660925#L1413

**Comment by Reinmar** [comment]
It was 10% previously: https://travis-ci.org/ckeditor/ckeditor5-utils/builds/189164026#L1408

File: src/emittermixin.js [hunk 1]
```diff
@@ -11,6 +11,12 @@ import EventInfo from './eventinfo';
 import uid from './uid';
 import priorities from './priorities';
 
+// Symbol for private `_listeningTo` property.
+const _listeningTo = Symbol();
```
Comment (Reinmar) [inline src/emittermixin.js]: Symbols should be named.

File: src/emittermixin.js [hunk 2]
```diff
@@ -357,6 +367,48 @@ const EmitterMixin = {
...
+
+	/**
+	 * Returns an `EmitterMixin` instance with given `id`, which this emitter is listening to. Returns `null` if
+	 * this emitter do not listen to any emitter identified by `id`.
+	 *
+	 * @protected
+	 * @param {String} id Unique emitter id.
+	 * @returns {EmitterMixin|null}
+	 */
+	_getEmitterListenedTo( id ) {
```
Comment (Reinmar) [inline src/emittermixin.js]: Please do not add more methods to the emitter mixin *object*. Add them to the module. Simply export them from this module and replace `this` with `subject` parameter.

The more methods we add to the object, the bigger chance that it's going clash or something. This is a mixin which should safely work with any class. Besides, it's also uglier.

File: src/emittermixin.js [hunk 3]
```diff
@@ -357,6 +367,48 @@ const EmitterMixin = {
...
 		}
+	},
+
+	/**
+	 * Returns an `EmitterMixin` instance with given `id`, which this emitter is listening to. Returns `null` if
+	 * this emitter do not listen to any emitter identified by `id`.
+	 *
+	 * @protected
+	 * @param {String} id Unique emitter id.
+	 * @returns {EmitterMixin|null}
```
Comment (Reinmar) [inline src/emittermixin.js]: Wrong return type.

File: src/emittermixin.js [hunk 4]
```diff
@@ -357,6 +367,48 @@ const EmitterMixin = {
...
+			return this[ _listeningTo ][ id ].emitter;
+		}
+
+		return null;
+	},
+
+	/**
+	 * Emitter's unique id.
+	 *
+	 * **Note:** `_emitterId` can be set only once.
```
Comment (Reinmar) [inline src/emittermixin.js]: So maybe create only a getter function which sets it if it's not set?

File: src/emittermixin.js (hunk 1 above)
Comment (Reinmar) [inline src/emittermixin.js]: You can also remove these comments then.

File: src/emittermixin.js (hunk 4 above)
Comment (scofalik) [inline src/emittermixin.js]: This will not work if you want to set an exact `_emitterId`. The question is whether we really need this functionallity.

File: src/emittermixin.js [hunk 5]
```diff
@@ -150,14 +156,18 @@ const EmitterMixin = {
...
+		if ( !this[ _listeningTo ] ) {
+			this[ _listeningTo ] = {};
 		}
 
-		if ( !( emitterId = emitter._emitterId ) ) {
-			emitterId = emitter._emitterId = uid();
+		emitters = this[ _listeningTo ];
+
+		if ( !emitter._emitterId ) {
+			emitter._emitterId = uid();
```
Comment (Reinmar) [inline src/emittermixin.js]: Yyy.... you sure that it should be `_emitterId`? We were supposed to make it a symbol.

Comment (scofalik) [inline src/emittermixin.js]: This got complicated in the process.

`_emitterId` is available through setter and getter (which are protected). If `_emitterId` is only a private property I should not write `emitter[ _emitterId ]` because then, from "this" emitter I am reaching `_emitterId` of `emitter` (different object).

That's why I introduced getter and setter which are protected. But to "hide" the property itself (so it's not enumerable) I still kept `_emitterId` `Symbol`.

Comment (scofalik) [inline src/emittermixin.js]: Another reason to introduce getter/setter is that we need it in `ProxyEmitter`, of course. Earlier I had `_setEmitterId` and `_getEmitterId` methods. Using them would be perhaps more clear, but it's silly to have such methods when those should be getters.

Comment (scofalik) [inline src/emittermixin.js]: So, to sum up, `Symbol` is used to save the property in the object, then "non-symbol" getter and setter are used to access the property.

Comment (Reinmar) [inline src/emittermixin.js]: Ah... right. So if you fix the other thing (setting the symbol by a separate function, not a class getter), then it will look ok.

File: src/emittermixin.js (hunk 4 above)
Comment (Reinmar) [inline src/emittermixin.js]: But is anyone using this? I mean - is there a code which needs to set an id?

Comment (scofalik) [inline src/emittermixin.js]: `ProxyEmitterMixin`

Comment (Reinmar) [inline src/emittermixin.js]: Hmm... thinking...

Comment (Reinmar) [inline src/emittermixin.js]: KK, here's explanation why we need the setter now: https://github.com/ckeditor/ckeditor5-utils/issues/120#issuecomment-271881520. Let's simplify this in the followup.

File: src/emittermixin.js (hunk 5 above)
Comment (scofalik) [inline src/emittermixin.js]: I don't understand what you mean in last comment, but I guess that for now it's fine ?

**Comment by scofalik** [comment]
I fixed few things.

**Comment by Reinmar** [comment]
UI tests fail after these changes.

```
✖ 2 tests failed

FAILED TESTS:
  createListDropdown
    constructor()
      ✖ listens to view#isOpen and reacts to DOM events (valid target)
        Chrome 55.0.2883 (Mac OS X 10.12.2)
      TypeError: Cannot convert undefined or null to object
          at Function.keys (<anonymous>)
          at Context.it (node_modules/ckeditor5-ui/tests/dropdown/list/createlistdropdown.js:9648:19)

      ✖ listens to view#isOpen and reacts to DOM events (invalid target)
        Chrome 55.0.2883 (Mac OS X 10.12.2)
      TypeError: Cannot convert undefined or null to object
          at Function.keys (<anonymous>)
          at Context.it (node_modules/ckeditor5-ui/tests/dropdown/list/createlistdropdown.js:9672:19)
```

Sooory.
